apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: my-nginx-app:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 80